name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: mytest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kubectl create namespace mytest
          kubectl create -f test/secret.yml -n ${NAMESPACE}
          echo "Namespaces:"
          kubectl get ns
          echo "Secrets:"
          kubectl get secrets -n ${NAMESPACE}
          echo "mytest-secret:"
          kubectl describe secret mytest-secret -n ${NAMESPACE}

